from enum import Enum

class DocumentStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING = "PENDING"
    PARTIALLY_SIGNED = "PARTIALLY_SIGNED"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    CANCELED = "CANCELED"

class SignerStatus(str, Enum):
    PENDING = "PENDING"
    SIGNED = "SIGNED"
    REJECTED = "REJECTED"

class FieldType(str, Enum):
    SIGNATURE = "SIGNATURE"
    TEXT = "TEXT"
    DATE = "DATE"

class NotificationType(str, Enum):
    INVITATION = "INVITATION"
    REMINDER = "REMINDER"
    COMPLETION = "COMPLETION"
    REJECTION = "REJECTION"

class NotificationStatus(str, Enum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"

class AuditActorType(str, Enum):
    USER = "USER"
    SYSTEM = "SYSTEM"

class AuditEventType(str, Enum):
    USER_REGISTERED = "USER_REGISTERED"
    USER_LOGIN = "USER_LOGIN"
    DOCUMENT_CREATED = "DOCUMENT_CREATED"
    DOCUMENT_UPLOADED = "DOCUMENT_UPLOADED"
    SIGNER_ADDED = "SIGNER_ADDED"
    INVITATION_SENT = "INVITATION_SENT"
    DOCUMENT_VIEWED = "DOCUMENT_VIEWED"
    FIELD_COMPLETED = "FIELD_COMPLETED"
    DOCUMENT_SIGNED = "DOCUMENT_SIGNED"
    DOCUMENT_REJECTED = "DOCUMENT_REJECTED"
    DOCUMENT_COMPLETED = "DOCUMENT_COMPLETED"
    LINK_EXPIRED = "LINK_EXPIRED"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    NOTIFICATION_FAILED = "NOTIFICATION_FAILED"
